title: Louis Durston-Wyatt
tagline: MMath at Durham University
description: Undergraduate MMath student at Durham University

url: "https://louisdw.xyz"
baseurl: ""
lang: en-GB

theme: jekyll-theme-cayman

logo: "/assets/images/louis.JPEG"

author:
  name: Louis Durston-Wyatt

social:
  name: Louis Durston-Wyatt
  links:
    - https://www.linkedin.com/in/louis-durston-wyatt-a529b03b7/
    - https://github.com/louisd-w

google_analytics: G-71LCJDTNQ1

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
