title: Louis Durston-Wyatt
description: Undegraduate MMath student at Durham University
theme: jekyll-theme-cayman

url: "https://louisdw.xyz"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
